# Generated by Django 4.0.5 on 2022-06-25 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_name', models.CharField(max_length=100, verbose_name='name of driver')),
                ('driver_phone_number', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='phone number of driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField(verbose_name='amount of transaction')),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 21, 32, 8, 789643, tzinfo=utc), verbose_name='date of transaction')),
                ('is_received', models.BooleanField(verbose_name='amount given or received')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_name', models.CharField(max_length=100, verbose_name='name of party')),
                ('party_phone_number', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='phone number of party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField(verbose_name='amount of transaction')),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 21, 32, 8, 789643, tzinfo=utc), verbose_name='date of transaction')),
                ('is_received', models.BooleanField(verbose_name='amount given or received')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_name', models.CharField(max_length=100, verbose_name='name of supplier')),
                ('supplier_phone_number', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='phone number of supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField(verbose_name='amount of transaction')),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 21, 32, 8, 789643, tzinfo=utc), verbose_name='date of transaction')),
                ('is_received', models.BooleanField(verbose_name='amount given or received')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatadata.party')),
            ],
        ),
    ]
